# Generated by Django 3.1 on 2021-05-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField(blank=True, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
